# Generated by Django 3.2.10 on 2023-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadfunction',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
