# Generated by Django 3.2.10 on 2023-04-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0003_alter_quadfunction_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadfunction',
            name='x1_range',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quadfunction',
            name='x2_range',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quadfunction',
            name='y1_range',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quadfunction',
            name='y2_range',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
