# Generated by Django 3.2.10 on 2023-06-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0004_auto_20230419_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadfunction',
            name='end_x',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quadfunction',
            name='range_plot',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quadfunction',
            name='start_x',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
