# Generated by Django 3.2.10 on 2023-06-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0005_auto_20230601_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadfunction',
            name='range_plot',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
