# Generated by Django 3.2.10 on 2023-06-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0006_alter_quadfunction_range_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadfunction',
            name='end_x',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='quadfunction',
            name='range_plot',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='quadfunction',
            name='start_x',
            field=models.SmallIntegerField(default=-5),
        ),
    ]
