# Generated by Django 3.2.10 on 2023-06-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0007_auto_20230601_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadfunction',
            name='end_x',
            field=models.SmallIntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='quadfunction',
            name='range_plot',
            field=models.FloatField(blank=True, default=0.1),
        ),
        migrations.AlterField(
            model_name='quadfunction',
            name='start_x',
            field=models.SmallIntegerField(blank=True, default=-5),
        ),
    ]
