# Generated by Django 3.2.10 on 2023-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0010_auto_20230609_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadfunction',
            name='range_plot',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
    ]
