# Generated by Django 3.2.10 on 2023-06-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0011_alter_quadfunction_range_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadfunction',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
